### ISSUE TITLE
Wrapped errors diff output is confusing

### ISSUE THREAD

**Issue by dprotaso** [google/go-cmp#202] opened 2020-05-19 20:19 UTC
Two errors with the same messsage but constructed differently when compared produce a diff that looks identical

https://play.golang.org/p/i3y-6_rqonr

```go
package main

import (
	"fmt"
	"errors"
	
	"github.com/google/go-cmp/cmp"
)

func main() {
	e1 := errors.New("Hello world!")
	e2 := fmt.Errorf("Hello %w", errors.New("world!"))
	
	
	fmt.Println(cmp.Diff(e1, e2))
}
```

Results in  

```diff
 interface{}(
- 	e"Hello world!",
+ 	e"Hello world!",
  )
```

**Comment by dsnet** [comment] 2020-05-19 20:20
Thanks for the report. It is a known issue with the reporter that it needs to do more work trying to disambiguate cases like these.

**Comment by dsnet** [comment] 2020-06-09 17:42
Closing as duplicate of #194

**Closed by dsnet** 2020-06-09 17:42 UTC
Labels: help wanted
