### ISSUE TITLE
cmp: Reporter's use of anonymous interface argument creates poor display output in godoc

### ISSUE THREAD

**Issue by mdlayher** [google/go-cmp#135] opened 2019-03-22 05:08 UTC
As of now, the index section on a local `godoc -http` instance and on https://godoc.org/github.com/google/go-cmp/cmp makes the Reporter link appear as such:

![Selection_016](https://user-images.githubusercontent.com/1926905/54801716-97cd2c80-4c3e-11e9-8746-6f000227911b.png)

This is pretty unfortunate, but I'm not sure if the correct answer is to fix godoc, give this interface a proper type, or perhaps both. I didn't file an issue on golang/go as of yet because I'm not sure what the best path forward is.

**Comment by dsnet** [comment] 2019-03-22 05:32
I would say that this is a bug with [github.com/golang/gddo](github.com/golang/gddo), which is the service that runs godoc.org. The unfortunate problem with godoc is that there are many implementations, and they unfortunately share little code, so fixing this in one place needs to be replicated again in another. It's been a long-term goal of mine to unify the godocs, but one can only do so much.

For example, the problem that you are describing is [fixed in the `go doc` commandline tool](https://github.com/golang/go/commit/84743c348b0a4a7ed1ea3d7122feb757ccc7ebae):
```
$ go doc | grep Reporter
    func Reporter(r interface{ ... }) Option
```
but is clearly not addressed in `gddo`.

**Comment by dsnet** [comment] 2019-03-22 05:39
\cc @dmitshur

**Comment by mdlayher** [comment] 2019-03-22 13:56
I see! It does seem to be reproducible for me on https://github.com/golang/tools/tree/master/godoc as well, but perhaps the two projects share some code somewhere that is causing this. Thanks for clarifying though.

**Comment by dsnet** [comment] 2019-06-10 17:52
Going to close this since the problem is fundamentally with godoc. @dmitshur and I hopefully to address some `godoc` issues in the next quarter or two.

**Closed by dsnet** 2019-06-10 17:52 UTC

**Comment by dmitshur** [comment] 2019-06-10 17:56
@dsnet Do we have an upstream issue for [`x/tools/cmd/godoc`](https://goissues.org/golang.org/x/tools/cmd/godoc) (or a lower-level component) for this, so we don't lose track of it? (We don't need a separate one for gddo.)

**Comment by dsnet** [comment] 2019-06-10 18:06
Done. golang/go#32532

**Comment by dfawley** [comment] 2019-11-05 15:31
@dsnet is there any reason _not_ to name the interface parameter type for `Reporter`?  I agree godoc could be handling this more gracefully but it's also pretty unusual for a function to accept a complex interface as an inline-defined type.  This is precisely the situation where naming interfaces is advised.
