### ISSUE TITLE
godocs on cmp.Reporter are busted

### ISSUE THREAD

**Issue by jmhodges** [google/go-cmp#164] opened 2019-10-08 22:18 UTC
The formatting of the godocs around cmp.Reporter are busted.

Screenshot attached.

<img width="695" alt="Screen Shot 2019-10-08 at 3 18 21 PM" src="https://user-images.githubusercontent.com/598/66437557-df4eb680-e9de-11e9-8a96-62e0cf3e8872.png">

**Comment by dsnet** [comment] 2019-10-08 22:19
Duplicate of https://github.com/golang/go/issues/32532

**Closed by dsnet** 2019-10-08 22:19 UTC
