### ISSUE TITLE
Compare errors 

### ISSUE THREAD

**Issue by lmittmann** [google/go-cmp#289] opened 2022-03-14 07:55 UTC
Error comparing is not very well supported by this package. There is `cmpopts.EquateErrors` however, this requires the error to check for to be exported, which is not always the case. 

Would you accept a PR that adds a `cmp.Option` to compare errors by their `.Error()` string?

**Comment by dsnet** [comment] 2022-03-14 08:16
Hi @lmittmann, thank you for the issue.

I'm philosophically opposed to adding such a feature as it makes it easier to write brittle tests.

A vast majority of libraries do not cover the text of an error within their compatibility guarantees, which means that it could change over time. The standard library itself has certainly changed the text of errors periodically over time. During my time at Google, a regular source of frustration was modifying an error in a widely used package and discovering that dozens (sometimes hundreds of brittle tests would all break.

In general:
* If you really need to test that a specific error occurs, then you should make a case to the library author why that error should be detectable and petition that it be exported, or
* settle for simply detecting that **any** error occurred, but not that a **specific** error occurred (see [`cmpopts.AnyError`](https://pkg.go.dev/github.com/google/go-cmp/cmp/cmpopts#AnyError)).

If you really want to do an error text comparison, you could do something like the following:
```go
// MatchError reports equality with any error that has sub-string match.
type MatchError string

func (e MatchError) Error() string     { return string(e)  }
func (e MatchError) Is(err error) bool { return err != nil && strings.Contains(err.Error(), string(e)) }
```
However, I don't think we should add this to `cmpopts`.

**Comment by lmittmann** [comment] 2022-03-14 08:59
Hi @dsnet, I totally agree with you that error checking by comparing error strings is not ideal. However, if checking for any error is not enough and you don't have control over the API this is the only way for unexported errors. Changing this is utopian - the vast majority of errors in the stdlib alone is unexported.

**Comment by dsnet** [comment] 2022-03-14 16:45
I'm going to close this as working as intended.

We rather aim for utopian, than providing something that's going to encourage the creation of brittle tests. People may reasonably differ on this, but the overall philosophy of this library has been to make it hard to write tests that depends on unexported artifacts and we're going to consistently stay with that.

The alternative is 3 lines, which doesn't seem that onerous.

**Closed by dsnet** 2022-03-14 16:45 UTC
