### ISSUE TITLE
Trouble getting Transformer with errors.Unwrap working

### ISSUE THREAD

**Issue by nhooyr** [google/go-cmp#174] opened 2019-12-14 00:13 UTC
```go
// CmpDiff compares exp to act and returns a human readable string representing their diff.
// https://github.com/google/go-cmp/issues/40#issuecomment-328615283
func CmpDiff(exp, act interface{}, opts ...cmp.Option) string {
	opts = append(opts, cmp.Transformer("unwrapErr", unwrapErr), DeepAllowUnexported(exp, act))
	return cmp.Diff(exp, act, opts...)
}

func DeepAllowUnexported(vs ...interface{}) cmp.Option {
	m := make(map[reflect.Type]struct{})
	for _, v := range vs {
		structTypes(reflect.ValueOf(v), m)
	}
	var typs []interface{}
	for t := range m {
		typs = append(typs, reflect.New(t).Elem().Interface())
	}
	return cmp.AllowUnexported(typs...)
}

func structTypes(v reflect.Value, m map[reflect.Type]struct{}) {
	if !v.IsValid() {
		return
	}
	switch v.Kind() {
	case reflect.Ptr:
		if !v.IsNil() {
			structTypes(v.Elem(), m)
		}
	case reflect.Interface:
		if !v.IsNil() {
			structTypes(v.Elem(), m)
		}
	case reflect.Slice, reflect.Array:
		for i := 0; i < v.Len(); i++ {
			structTypes(v.Index(i), m)
		}
	case reflect.Map:
		for _, k := range v.MapKeys() {
			structTypes(v.MapIndex(k), m)
		}
	case reflect.Struct:
		m[v.Type()] = struct{}{}
		for i := 0; i < v.NumField(); i++ {
			structTypes(v.Field(i), m)
		}
	}
}

func unwrapErr(werr interface {
	error
	Unwrap() error
}) error {
	err := error(werr)
	uerr := errors.Unwrap(werr)
	for uerr != nil {
		err = uerr
		uerr = errors.Unwrap(err)
	}
	return err
}
```

```go
func TestCmpDiff(t *testing.T) {
	t.Parallel()

	t.Log(CmpDiff(io.EOF, fmt.Errorf("failed: %w", io.EOF)))
}
```

The above test outputs:

```
    assert_test.go:12:   interface{}(
        - 	e"EOF",
        + 	e"failed: EOF",
          )
```

But the diff should be empty since the transformer should transform each wrapped error into a normal error and the comparison should be done on that.

**Comment by dsnet** [comment] 2019-12-16 08:38
This is a duplicate of #161 and fundamentally due to a gotcha in the Go language. See https://github.com/google/go-cmp/issues/161#issuecomment-537786843.

You can work around this by doing the following:
```go
cmp.FilterValues(func(x, y interface{}) bool {
	// Use interface{} instead of error as the input type since we want to check
	// whether the underlying concrete types happen to implement the error interface.
	_, ok1 := x.(error)
	_, ok2 := y.(error)
	return ok1 && ok2
}, cmp.Comparer(func(x, y interface{}) bool {
	// It is safe to directly assert to the error interface since the previous filter
	// ensures that only error types get to this point.
	xe := x.(error)
	ye := y.(error)
	return errors.Is(xe, ye) || errors.Is(ye, xe)
})
```
See #178

**Closed by dsnet** 2019-12-16 08:38 UTC

**Comment by nhooyr** [comment] 2019-12-16 16:34
Makes sense, thanks.
