### ISSUE TITLE
Output difference in a new struct

### ISSUE THREAD

**Issue by kaspergyselinck** [google/go-cmp#114] opened 2019-02-19 12:57 UTC
Would it be possible to have a function return a struct where the only properties containing values are the differences between 2 structs?
The human readable string that is returned for the Diff function is already useful, but the function comment indicates it's not reliable.

Example of how this could be useful:
You need a version timeline of a data struct, and you only want to save the differences for every "version" of a struct.

**Comment by dsnet** [comment] 2019-02-19 12:59
Duplicate of #92

**Closed by dsnet** 2019-02-19 12:59 UTC
