### ISSUE TITLE
cmpopts.IgnoreFields failure on sub fields with imports

### ISSUE THREAD

**Issue by yonderblue** [google/go-cmp#255] opened 2021-03-23 09:49 UTC
In this example https://play.golang.com/p/OrDVXWIOtZy
which works, if I change A and B to be a type imported from another package, it fails.
(Sorry I can not get a repro directly in playground)

Note if I use IgnoreFields with a field directly on A in my test it works fine, so it is related to the sub field selection.

**Comment by dsnet** [comment] 2021-03-24 04:09
Without a reproduction, it's hard for us to speak meaningfully here.

BTW, the Go playground supports multiple files: https://play.golang.org/p/GBMO9HKN3hZ

Can you provide a reproduction?

**Comment by dsnet** [comment] 2021-04-09 07:36
Closing as inactionable due to lack of reproduction.

**Closed by dsnet** 2021-04-09 07:36 UTC
Labels: waiting-for-info
